import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string
const supabasePublishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string

if (!supabaseUrl || !supabasePublishableKey) {
  throw new Error('Missing Supabase environment variables: ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set')
}

export const supabase = createClient(supabaseUrl, supabasePublishableKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
})

// Database types (will be generated by Supabase CLI)
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          name: string
          role: 'ADMIN' | 'MANAGER' | 'CLIENT'
          avatar: string | null
          created_at: string
          updated_at: string
          last_login: string | null
        }
        Insert: {
          id: string
          name: string
          role?: 'ADMIN' | 'MANAGER' | 'CLIENT'
          avatar?: string | null
          created_at?: string
          updated_at?: string
          last_login?: string | null
        }
        Update: {
          id?: string
          name?: string
          role?: 'ADMIN' | 'MANAGER' | 'CLIENT'
          avatar?: string | null
          created_at?: string
          updated_at?: string
          last_login?: string | null
        }
      }
      clients: {
        Row: {
          id: string
          user_id: string | null
          company_name: string
          contact_name: string
          email: string
          phone: string | null
          website: string | null
          sector: string
          size: string
          address: any | null
          lead_source: string
          acquisition_cost: number | null
          lifetime_value: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          company_name: string
          contact_name: string
          email: string
          phone?: string | null
          website?: string | null
          sector: string
          size: string
          address?: any | null
          lead_source: string
          acquisition_cost?: number | null
          lifetime_value?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          company_name?: string
          contact_name?: string
          email?: string
          phone?: string | null
          website?: string | null
          sector?: string
          size?: string
          address?: any | null
          lead_source?: string
          acquisition_cost?: number | null
          lifetime_value?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          name: string
          description: string
          client_id: string
          service_level: number
          status: 'PLANNING' | 'ACTIVE' | 'REVIEW' | 'COMPLETED' | 'CANCELLED'
          start_date: string
          expected_end_date: string
          actual_end_date: string | null
          budget: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description: string
          client_id: string
          service_level: number
          status?: 'PLANNING' | 'ACTIVE' | 'REVIEW' | 'COMPLETED' | 'CANCELLED'
          start_date: string
          expected_end_date: string
          actual_end_date?: string | null
          budget: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string
          client_id?: string
          service_level?: number
          status?: 'PLANNING' | 'ACTIVE' | 'REVIEW' | 'COMPLETED' | 'CANCELLED'
          start_date?: string
          expected_end_date?: string
          actual_end_date?: string | null
          budget?: number
          created_at?: string
          updated_at?: string
        }
      }
      campaigns: {
        Row: {
          id: string
          name: string
          platform: 'GOOGLE' | 'META'
          external_id: string
          status: 'ACTIVE' | 'PAUSED' | 'ENDED'
          budget: number
          spent: number
          impressions: number
          clicks: number
          conversions: number
          cpc: number
          ctr: number
          roas: number
          start_date: string
          end_date: string | null
          last_sync_at: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          platform: 'GOOGLE' | 'META'
          external_id: string
          status?: 'ACTIVE' | 'PAUSED' | 'ENDED'
          budget: number
          spent?: number
          impressions?: number
          clicks?: number
          conversions?: number
          cpc?: number
          ctr?: number
          roas?: number
          start_date: string
          end_date?: string | null
          last_sync_at?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          platform?: 'GOOGLE' | 'META'
          external_id?: string
          status?: 'ACTIVE' | 'PAUSED' | 'ENDED'
          budget?: number
          spent?: number
          impressions?: number
          clicks?: number
          conversions?: number
          cpc?: number
          ctr?: number
          roas?: number
          start_date?: string
          end_date?: string | null
          last_sync_at?: string
          created_at?: string
          updated_at?: string
        }
      }
      leads: {
        Row: {
          id: string
          name: string
          email: string
          phone: string | null
          company: string | null
          source: string
          stage: 'NEW' | 'QUALIFIED' | 'PROPOSAL' | 'NEGOTIATION' | 'WON' | 'LOST'
          value: number | null
          notes: string | null
          assigned_to: string | null
          campaign_id: string | null
          client_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          email: string
          phone?: string | null
          company?: string | null
          source: string
          stage?: 'NEW' | 'QUALIFIED' | 'PROPOSAL' | 'NEGOTIATION' | 'WON' | 'LOST'
          value?: number | null
          notes?: string | null
          assigned_to?: string | null
          campaign_id?: string | null
          client_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          email?: string
          phone?: string | null
          company?: string | null
          source?: string
          stage?: 'NEW' | 'QUALIFIED' | 'PROPOSAL' | 'NEGOTIATION' | 'WON' | 'LOST'
          value?: number | null
          notes?: string | null
          assigned_to?: string | null
          campaign_id?: string | null
          client_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      user_role: 'ADMIN' | 'MANAGER' | 'CLIENT'
      project_status: 'PLANNING' | 'ACTIVE' | 'REVIEW' | 'COMPLETED' | 'CANCELLED'
      project_phase_status: 'PENDING' | 'ACTIVE' | 'COMPLETED'
      lead_stage: 'NEW' | 'QUALIFIED' | 'PROPOSAL' | 'NEGOTIATION' | 'WON' | 'LOST'
      campaign_platform: 'GOOGLE' | 'META'
      campaign_status: 'ACTIVE' | 'PAUSED' | 'ENDED'
    }
  }
}