import { Check, Clock3, X } from 'lucide-react'
import { MissionStatusBadge } from './MissionStatusBadge'
import { approvalStatusLabel, approvalTypeLabel } from '@/lib/action-engine/missionRules'
import type { MissionApproval } from '@/types/actionEngine'

export function MissionApprovalsPanel({ approvals, canWrite, busyApprovalId, onDecision }: {
  approvals: MissionApproval[]; canWrite: boolean; busyApprovalId?: string; onDecision: (approval: MissionApproval, decision: 'approved' | 'rejected') => void
}) {
  return <section className="border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h2 className="font-semibold text-slate-950">Histórico de decisões</h2><p className="mt-1 text-xs text-slate-500">Autorizações e recusas registradas para esta missão.</p></div><span className="border border-amber-200 bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-800">{approvals.filter(item => item.status === 'pending').length} pendentes</span></div>{approvals.length === 0 ? <p className="p-5 text-sm text-slate-500">Nenhuma aprovação registrada.</p> : <div className="divide-y divide-slate-200">{approvals.map(approval => <article key={approval.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-sm font-semibold text-slate-900"><Clock3 className="h-4 w-4 text-amber-600" /> {approvalTypeLabel[approval.approvalType] ?? approval.approvalType}</div>{typeof approval.requestedPayload?.decisionSummary === 'object' && approval.requestedPayload.decisionSummary ? <p className="mt-1 text-xs text-slate-500">{String(Reflect.get(approval.requestedPayload.decisionSummary, 'headline') ?? 'Plano revisável')}</p> : null}</div><MissionStatusBadge label={approvalStatusLabel[approval.status] ?? approval.status} tone={approval.status === 'approved' ? 'success' : approval.status === 'pending' ? 'warning' : approval.status === 'rejected' ? 'danger' : 'neutral'} /></div>{canWrite && approval.status === 'pending' && approval.approvalType !== 'plan' && approval.approvalType !== 'replan' && <div className="mt-3 flex gap-2"><button disabled={busyApprovalId === approval.id} onClick={() => onDecision(approval, 'approved')} className="inline-flex h-8 items-center gap-1 bg-emerald-700 px-3 text-xs font-semibold text-white"><Check className="h-3 w-3" /> Aprovar</button><button disabled={busyApprovalId === approval.id} onClick={() => onDecision(approval, 'rejected')} className="inline-flex h-8 items-center gap-1 border border-red-200 px-3 text-xs font-semibold text-red-700"><X className="h-3 w-3" /> Rejeitar</button></div>}</article>)}</div>}</section>
}
