import { useState } from 'react'
import { PauseCircle, PlayCircle } from 'lucide-react'
import { MissionBudgetBurnDown } from './MissionBudgetBurnDown'
import { MissionReadinessBlockers } from './MissionReadinessBlockers'
import type { MissionCapabilityControl, MissionOperationalControls as Controls } from '@/types/actionEngine'

export function MissionOperationalControls({ controls, busyCapability, onCapabilityControl }: {
  controls: Controls; busyCapability?: string;
  onCapabilityControl: (capability: MissionCapabilityControl, disabled: boolean, reason: string) => void
}) {
  const [pending, setPending] = useState<{ capability: MissionCapabilityControl; disabled: boolean } | null>(null)
  const [reason, setReason] = useState('')
  function confirm() { if (!pending || reason.trim().length < 3) return; onCapabilityControl(pending.capability, pending.disabled, reason.trim()) }
  return <div className="grid gap-6 xl:grid-cols-2"><MissionBudgetBurnDown budget={controls.budget} /><div className="space-y-6"><MissionReadinessBlockers readiness={controls.readiness} />{controls.canManagePolicy && controls.capabilities.length ? <section className="border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold text-slate-950">Controles por capacidade</h2><p className="mt-1 text-xs text-slate-500">Pausa uma versão exata sem interromper as demais funções.</p></div><div className="divide-y divide-slate-200">{controls.capabilities.map(capability => <div key={`${capability.capabilityKey}@${capability.capabilityVersion}`} className="p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-mono text-xs font-semibold text-slate-800">{capability.capabilityKey}@{capability.capabilityVersion}</p><p className={`mt-1 text-xs ${capability.disabled ? 'text-red-700' : 'text-emerald-700'}`}>{capability.disabled ? 'Pausada' : 'Ativa'}</p></div><button disabled={busyCapability === `${capability.capabilityKey}@${capability.capabilityVersion}`} onClick={() => { setPending({ capability, disabled: !capability.disabled }); setReason('') }} className={`inline-flex h-8 items-center gap-1 border px-3 text-xs font-semibold ${capability.disabled ? 'border-emerald-200 text-emerald-700' : 'border-red-200 text-red-700'}`}>{capability.disabled ? <PlayCircle className="h-3 w-3" /> : <PauseCircle className="h-3 w-3" />}{capability.disabled ? 'Reativar' : 'Pausar'}</button></div>{pending?.capability.capabilityKey === capability.capabilityKey && pending.capability.capabilityVersion === capability.capabilityVersion ? <div className="mt-3 border border-slate-200 bg-slate-50 p-3"><label className="text-xs font-semibold text-slate-700">Motivo da alteração<textarea aria-label={`Motivo para ${capability.capabilityKey}`} value={reason} onChange={event => setReason(event.target.value)} className="mt-2 min-h-20 w-full border border-slate-300 bg-white p-2" /></label><div className="mt-2 flex gap-2"><button disabled={reason.trim().length < 3} onClick={confirm} className="h-8 bg-slate-900 px-3 text-xs font-semibold text-white disabled:opacity-50">Confirmar controle</button><button onClick={() => setPending(null)} className="h-8 px-3 text-xs font-semibold text-slate-600">Cancelar</button></div></div> : null}</div>)}</div></section> : null}</div></div>
}
