INSERT INTO public.action_packs (key,name,description)
VALUES ('funnel_nurture','Funnel + Nurture','Criação governada de funil, copy citada, sequência e gatilho de nutrição.')
ON CONFLICT (key) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,updated_at=NOW();

WITH pack AS (SELECT id FROM public.action_packs WHERE key='funnel_nurture')
INSERT INTO public.action_pack_versions (pack_id,semantic_version,schema_version,outcome_type,status,definition,content_hash,published_at)
SELECT pack.id,'1.0.0',1,'qualified_demand_system','published',$definition$
{
  "schemaVersion":1,
  "parameterSchema":{"type":"object","required":["icp","offer"],"properties":{"icp":{"type":"string","minLength":3},"offer":{"type":"string","minLength":3},"targetOutcome":{"enum":["qualified_lead","reply","opportunity"]},"observationDays":{"type":"integer","minimum":1,"maximum":90},"maxTotalCostBrl":{"type":"string","format":"decimal"},"maxHumanHours":{"type":"string","format":"decimal"},"humanHourlyRateBrl":{"type":"string","format":"decimal"},"expectedReplyRate":{"type":"number","minimum":0,"maximum":1},"maximumOptOutRate":{"type":"number","minimum":0,"maximum":1}}},
  "readinessSpec":{"requiredModules":["crm","automations"],"requiredConnections":["email"],"requiredKnowledge":["company.icp","company.offer","brand.rules"],"correctionLinks":{"email":"/integrations","contract":"/platform/contracts","knowledge":"/knowledge"}},
  "topologyTemplate":{"steps":[
    {"stepKey":"pack.readiness","capabilityKey":"system.readiness.check","capabilityVersion":1,"dependsOn":[],"approvalRequired":false,"protected":true,"defaultParameters":{"requiredModules":["crm","automations"],"requiredConnections":["email"]}},
    {"stepKey":"pack.inspect","capabilityKey":"crm.pipeline.inspect","capabilityVersion":1,"dependsOn":["pack.readiness"],"approvalRequired":false,"protected":true,"defaultParameters":{}},
    {"stepKey":"pack.baseline","capabilityKey":"crm.pipeline.inspect","capabilityVersion":1,"dependsOn":["pack.inspect"],"approvalRequired":false,"protected":true,"defaultParameters":{}},
    {"stepKey":"pack.simulate_funnel","capabilityKey":"crm.pipeline.simulate","capabilityVersion":1,"dependsOn":["pack.baseline"],"approvalRequired":false,"protected":true,"defaultParameters":{"artifactRef":"resolvedParameters.funnelNurtureArtifacts.funnel"}},
    {"stepKey":"pack.draft_funnel","capabilityKey":"crm.pipeline.create_draft","capabilityVersion":1,"dependsOn":["pack.simulate_funnel"],"approvalRequired":false,"protected":true,"defaultParameters":{"artifactRef":"resolvedParameters.funnelNurtureArtifacts.funnel"}},
    {"stepKey":"pack.draft_email_1","capabilityKey":"email.template.create_draft","capabilityVersion":1,"dependsOn":["pack.draft_funnel"],"approvalRequired":false,"protected":true,"defaultParameters":{"artifactRef":"resolvedParameters.funnelNurtureArtifacts.emails.0"}},
    {"stepKey":"pack.draft_email_2","capabilityKey":"email.template.create_draft","capabilityVersion":1,"dependsOn":["pack.draft_email_1"],"approvalRequired":false,"protected":true,"defaultParameters":{"artifactRef":"resolvedParameters.funnelNurtureArtifacts.emails.1"}},
    {"stepKey":"pack.draft_email_3","capabilityKey":"email.template.create_draft","capabilityVersion":1,"dependsOn":["pack.draft_email_2"],"approvalRequired":false,"protected":true,"defaultParameters":{"artifactRef":"resolvedParameters.funnelNurtureArtifacts.emails.2"}},
    {"stepKey":"pack.draft_sequence","capabilityKey":"crm.sequence.create_draft","capabilityVersion":1,"dependsOn":["pack.draft_email_3"],"approvalRequired":false,"protected":true,"defaultParameters":{"artifactRef":"resolvedParameters.funnelNurtureArtifacts.sequence"}},
    {"stepKey":"pack.simulate_sequence","capabilityKey":"crm.sequence.simulate","capabilityVersion":1,"dependsOn":["pack.draft_sequence"],"approvalRequired":false,"protected":true,"defaultParameters":{"sequenceId":"binding:pack.draft_sequence.entityId","versionId":"binding:pack.draft_sequence.versionId","expectedContentHash":"binding:pack.draft_sequence.contentHash"}},
    {"stepKey":"pack.draft_flow","capabilityKey":"automation.flow.create_draft","capabilityVersion":1,"dependsOn":["pack.simulate_sequence"],"approvalRequired":false,"protected":true,"defaultParameters":{"artifactRef":"resolvedParameters.funnelNurtureArtifacts.automation","sequenceVersionId":"binding:pack.draft_sequence.versionId"}},
    {"stepKey":"pack.simulate_flow","capabilityKey":"automation.flow.simulate","capabilityVersion":1,"dependsOn":["pack.draft_flow"],"approvalRequired":false,"protected":true,"defaultParameters":{"flowId":"binding:pack.draft_flow.entityId","versionId":"binding:pack.draft_flow.versionId","expectedContentHash":"binding:pack.draft_flow.contentHash"}},
    {"stepKey":"pack.approve_publication","capabilityKey":"system.approval.await","capabilityVersion":1,"dependsOn":["pack.simulate_flow"],"approvalRequired":true,"protected":true,"defaultParameters":{"approvalType":"plan","subject":{"artifactSet":"funnel_nurture"}}},
    {"stepKey":"pack.publish_funnel","capabilityKey":"crm.pipeline.publish","capabilityVersion":1,"dependsOn":["pack.approve_publication"],"approvalRequired":true,"protected":true,"defaultParameters":{"versionId":"binding:pack.draft_funnel.versionId","expectedContentHash":"binding:pack.draft_funnel.contentHash"}},
    {"stepKey":"pack.publish_email_1","capabilityKey":"email.template.publish","capabilityVersion":1,"dependsOn":["pack.publish_funnel"],"approvalRequired":true,"protected":true,"defaultParameters":{"templateId":"binding:pack.draft_email_1.entityId","expectedContentHash":"binding:pack.draft_email_1.contentHash"}},
    {"stepKey":"pack.publish_email_2","capabilityKey":"email.template.publish","capabilityVersion":1,"dependsOn":["pack.publish_email_1"],"approvalRequired":true,"protected":true,"defaultParameters":{"templateId":"binding:pack.draft_email_2.entityId","expectedContentHash":"binding:pack.draft_email_2.contentHash"}},
    {"stepKey":"pack.publish_email_3","capabilityKey":"email.template.publish","capabilityVersion":1,"dependsOn":["pack.publish_email_2"],"approvalRequired":true,"protected":true,"defaultParameters":{"templateId":"binding:pack.draft_email_3.entityId","expectedContentHash":"binding:pack.draft_email_3.contentHash"}},
    {"stepKey":"pack.publish_sequence","capabilityKey":"crm.sequence.publish","capabilityVersion":1,"dependsOn":["pack.publish_email_3"],"approvalRequired":true,"protected":true,"defaultParameters":{"sequenceId":"binding:pack.draft_sequence.entityId","versionId":"binding:pack.draft_sequence.versionId","expectedContentHash":"binding:pack.draft_sequence.contentHash"}},
    {"stepKey":"pack.publish_flow","capabilityKey":"automation.flow.publish","capabilityVersion":1,"dependsOn":["pack.publish_sequence"],"approvalRequired":true,"protected":true,"defaultParameters":{"flowId":"binding:pack.draft_flow.entityId","versionId":"binding:pack.draft_flow.versionId","expectedContentHash":"binding:pack.draft_flow.contentHash"}},
    {"stepKey":"pack.wait_observation","capabilityKey":"system.signal.wait","capabilityVersion":1,"dependsOn":["pack.publish_flow"],"approvalRequired":false,"protected":true,"defaultParameters":{"durationHours":720}},
    {"stepKey":"pack.evaluate","capabilityKey":"system.evaluation.checkpoint","capabilityVersion":1,"dependsOn":["pack.wait_observation"],"approvalRequired":false,"protected":true,"defaultParameters":{"checkpointKey":"funnel_nurture_30d","targetRevenueBrl":"0"}}
  ]},
  "protectedStepKeys":["pack.readiness","pack.inspect","pack.baseline","pack.simulate_funnel","pack.draft_funnel","pack.draft_email_1","pack.draft_email_2","pack.draft_email_3","pack.draft_sequence","pack.simulate_sequence","pack.draft_flow","pack.simulate_flow","pack.approve_publication","pack.publish_funnel","pack.publish_email_1","pack.publish_email_2","pack.publish_email_3","pack.publish_sequence","pack.publish_flow","pack.wait_observation","pack.evaluate"],
  "extensionPoints":[{"key":"optional_scoring_fields","afterStepKey":"pack.inspect","beforeStepKey":"pack.baseline","allowedCapabilities":[{"key":"crm.lead.timeline.read","versions":[1]}],"maxAdditionalSteps":2},{"key":"internal_owner_tasks","afterStepKey":"pack.approve_publication","beforeStepKey":"pack.publish_funnel","allowedCapabilities":[{"key":"crm.task.create","versions":[1]},{"key":"crm.lead.assign_owner","versions":[1]}],"maxAdditionalSteps":2}],
  "allowedCapabilities":[{"key":"system.readiness.check","versions":[1],"required":true},{"key":"crm.pipeline.inspect","versions":[1],"required":true},{"key":"crm.pipeline.simulate","versions":[1],"required":true},{"key":"crm.pipeline.create_draft","versions":[1],"required":true},{"key":"email.template.create_draft","versions":[1],"required":true},{"key":"crm.sequence.create_draft","versions":[1],"required":true},{"key":"crm.sequence.simulate","versions":[1],"required":true},{"key":"automation.flow.create_draft","versions":[1],"required":true},{"key":"automation.flow.simulate","versions":[1],"required":true},{"key":"system.approval.await","versions":[1],"required":true},{"key":"crm.pipeline.publish","versions":[1],"required":true},{"key":"email.template.publish","versions":[1],"required":true},{"key":"crm.sequence.publish","versions":[1],"required":true},{"key":"automation.flow.publish","versions":[1],"required":true},{"key":"system.signal.wait","versions":[1],"required":true},{"key":"system.evaluation.checkpoint","versions":[1],"required":true},{"key":"crm.lead.timeline.read","versions":[1],"required":false},{"key":"crm.task.create","versions":[1],"required":false},{"key":"crm.lead.assign_owner","versions":[1],"required":false}],
  "metricSpec":{"primary":{"key":"qualified_demand_value_brl","unit":"BRL","attributionPolicy":{"version":1,"model":"last_touch","windowDays":30,"eligibleEventTypes":["qualified_lead","email_reply","opportunity_created"],"identityResolution":"exact_contact_or_declared_binding","currency":"BRL","lateEvents":"reopen_evaluation"},"attributionPolicyHash":"8cb4db97b02e1ad70d9b8946da8bf871e01d37f86c71c5dae75c996112dd97e2"},"operational":["published_artifact_count","simulated_contact_count","enrollment_readiness","funnel_conversion_baseline","reply_rate"],"guardrails":["opt_out_rate","complaint_rate","consent_blocks","suppression_blocks"],"unknownPolicy":"preserve_unknown_when_identity_unresolved"},
  "economicsSpec":{"currency":"BRL","formulas":{"totalCost":"sum(actual_cost_entries_brl)","valueCostRatio":"qualifiedDemandValueBrl/totalCost","valuePerHumanHour":"qualifiedDemandValueBrl/humanHours","interventionRate":"human_interventions/total_actions"},"zeroDenominator":"not_applicable","trackFromFirstRun":true},
  "policyDefaults":{"mode":"prepare","ownershipMode":"exclusive","conflictPolicy":"mission_wins","publicationApprovalRequired":true,"setupEnrollsExistingLeads":false,"activationContractFlag":"funnel_nurture_agent","activationCapabilitiesDisabledByDefault":true}
}
$definition$::jsonb,'d2f3f6fcd4a1778c8196737659d550f4886103ba78b6fb3db33a45a41675c97a',NOW()
FROM pack
ON CONFLICT (pack_id,semantic_version) DO NOTHING;

INSERT INTO public.action_capability_policies (
  organization_id,capability_key,capability_version,enabled,kill_switch,approval_override
)
SELECT organization.id, capability.key, 1, FALSE,FALSE,'always'
FROM public.organizations organization
CROSS JOIN (VALUES
  ('crm.pipeline.publish'),('email.template.publish'),('crm.sequence.publish'),('automation.flow.publish')
) capability(key)
ON CONFLICT (organization_id,capability_key,capability_version) DO NOTHING;
