import { describe,expect,it } from 'vitest'
import { aggregateCompositeMetricSnapshots,evaluateCompositeMission,type CompositePackEvaluation } from '../src/modules/action-engine/metrics/composite.js'
import type { PackMetricSnapshot } from '../src/modules/action-engine/metrics/collector.js'

const economics={producedValueBrl:'1000',totalExecutionCostBrl:'200',netValueBrl:'800',valueCostRatio:'5',valuePerHumanHourBrl:'1000',humanFreeExecutionRate:'0.5'}
const packs=(funnel:'continue'|'succeed'|'fail'|'block'|'pause'|'propose_replan'='succeed',campaign:typeof funnel='succeed'):CompositePackEvaluation[]=>[{packKey:'funnel_nurture',conclusion:funnel,reasons:[`funnel_${funnel}`],optional:false,dependsOn:[]},{packKey:'campaign_launch',conclusion:campaign,reasons:[`campaign_${campaign}`],optional:false,dependsOn:['funnel_nurture']}]
describe('composite Mission evaluator',()=>{
  it('succeeds only when required packs or explicit acceptance criteria succeed',()=>{expect(evaluateCompositeMission({packs:packs(),economics,maxTotalCostBrl:'500'}).conclusion).toBe('succeed');expect(evaluateCompositeMission({packs:packs('continue','continue'),economics,maxTotalCostBrl:'500',acceptanceCriteriaMet:true}).conclusion).toBe('succeed')})
  it('applies critical precedence and marks an upstream failure plus dependents',()=>{expect(evaluateCompositeMission({packs:packs('succeed','pause'),economics,maxTotalCostBrl:'500'}).conclusion).toBe('pause');const failed=evaluateCompositeMission({packs:packs('fail','continue'),economics,maxTotalCostBrl:'500'});expect(failed.conclusion).toBe('fail');expect(failed.affectedPacks).toEqual(['funnel_nurture','campaign_launch'])})
  it('pauses aggregate budget and cannot fabricate success from an optional failure',()=>{expect(evaluateCompositeMission({packs:packs(),economics:{...economics,totalExecutionCostBrl:'500.01'},maxTotalCostBrl:'500'}).reasons).toContain('composite_budget_breached');const optional=packs();optional[1]={...optional[1]!,optional:true,conclusion:'fail'};expect(evaluateCompositeMission({packs:optional,economics,maxTotalCostBrl:'500'}).conclusion).toBe('block')})
  it('replans only an affected pack and its dependents',()=>{const result=evaluateCompositeMission({packs:packs('propose_replan','continue'),economics,maxTotalCostBrl:'500'});expect(result.conclusion).toBe('propose_replan');expect(result.affectedPacks).toEqual(['funnel_nurture','campaign_launch'])})
  it('namespaces per-pack metrics and carries unknown blocking signals',()=>{const snapshot=(packKey:string,unknown:boolean):PackMetricSnapshot=>({packKey,measuredAt:'2026-08-30T00:00:00.000Z',metrics:{value:unknown?{kind:'unknown',reason:'missing',unit:'BRL'}:{kind:'known',value:'0',unit:'BRL'}},evidence:{},signals:{criticalGuardrailBreached:false,killSwitchActive:false,minimumSampleReached:true,offTrack:false,requiredMetricUnknownIsBlocking:unknown,reasons:unknown?['missing']:[]}});const combined=aggregateCompositeMetricSnapshots([snapshot('funnel_nurture',false),snapshot('campaign_launch',true)]);expect(combined.metrics).toHaveProperty('campaign_launch.value');expect(combined.signals.requiredMetricUnknownIsBlocking).toBe(true)})
})
