import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import type { LeadScoreDimension, LeadScoringOperator, LeadScoringRule } from '@/types/crm'

const eventOptions = [
  ['lead.created', 'Lead criado'], ['form.submitted', 'Formulário enviado'], ['lead.stage_changed', 'Etapa alterada'],
  ['lead.task_created', 'Tarefa criada'], ['lead.task_completed', 'Tarefa concluída'], ['lead.task_cancelled', 'Tarefa cancelada'],
  ['lead.task_reopened', 'Tarefa reaberta'], ['lead.interaction_recorded', 'Interação registrada'], ['email.opened', 'E-mail aberto'], ['email.clicked', 'E-mail clicado'],
] as const

export function ScoringRuleEditor({ modelId, onCreate }: { modelId: string; onCreate: (input: { modelId: string; name: string; dimension: LeadScoreDimension; eventType: string; points: number; fieldPath?: string; operator?: LeadScoringOperator; comparisonValue?: unknown }) => Promise<void> }) {
  const [name, setName] = useState('')
  const [dimension, setDimension] = useState<LeadScoreDimension>('intent')
  const [eventType, setEventType] = useState('lead.task_completed')
  const [points, setPoints] = useState('10')
  const [fieldPath, setFieldPath] = useState('')
  const [operator, setOperator] = useState<LeadScoringOperator | ''>('')
  const [comparisonValue, setComparisonValue] = useState('')
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const numericPoints = Number(points); if (!name.trim() || !Number.isInteger(numericPoints) || numericPoints === 0 || numericPoints < -100 || numericPoints > 100) { setError('Informe nome e pontos entre -100 e 100, exceto zero.'); return }; setSaving(true); setError(null); try { await onCreate({ modelId, name: name.trim(), dimension, eventType, points: numericPoints, fieldPath: fieldPath.trim() || undefined, operator: operator || undefined, comparisonValue: comparisonValue || undefined }); setName(''); setFieldPath(''); setComparisonValue('') } catch (saveError) { console.error(saveError); setError('Não foi possível criar a regra.') } finally { setSaving(false) } }
  return <form className="space-y-3 rounded-md border p-4" onSubmit={submit}><div className="grid gap-3 md:grid-cols-2"><div><label htmlFor="rule-name" className="text-sm font-medium">Nome da regra</label><Input id="rule-name" value={name} onChange={event => setName(event.target.value)} placeholder="Tarefa concluída" /></div><div><label htmlFor="rule-event" className="text-sm font-medium">Ação</label><select id="rule-event" className="mt-1 flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={eventType} onChange={event => setEventType(event.target.value)}>{eventOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></div><div className="grid gap-3 md:grid-cols-3"><div><label htmlFor="rule-dimension" className="text-sm font-medium">Dimensão</label><select id="rule-dimension" className="mt-1 flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={dimension} onChange={event => setDimension(event.target.value as LeadScoreDimension)}><option value="fit">Fit</option><option value="intent">Intenção</option></select></div><div><label htmlFor="rule-points" className="text-sm font-medium">Pontos</label><Input id="rule-points" type="number" min="-100" max="100" value={points} onChange={event => setPoints(event.target.value)} /></div><div><label htmlFor="rule-field" className="text-sm font-medium">Campo (opcional)</label><Input id="rule-field" value={fieldPath} onChange={event => setFieldPath(event.target.value)} placeholder="payload.source" /></div></div><div className="grid gap-3 md:grid-cols-2"><div><label htmlFor="rule-operator" className="text-sm font-medium">Condição</label><select id="rule-operator" className="mt-1 flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={operator} onChange={event => setOperator(event.target.value as LeadScoringOperator | '')}><option value="">Sempre</option><option value="equals">Igual a</option><option value="contains">Contém</option><option value="exists">Existe</option><option value="greater_than">Maior que</option><option value="less_than">Menor que</option></select></div><div><label htmlFor="rule-comparison" className="text-sm font-medium">Valor da condição</label><Input id="rule-comparison" value={comparisonValue} onChange={event => setComparisonValue(event.target.value)} /></div></div>{error && <p className="text-sm text-red-600" role="alert">{error}</p>}<Button type="submit" disabled={saving}>{saving ? 'Salvando...' : 'Nova regra'}</Button></form>
}

export function ScoringRuleRow({ rule, onDeactivate }: { rule: LeadScoringRule; onDeactivate: (id: string) => Promise<void> }) { return <div className="flex flex-wrap items-center justify-between gap-3 rounded-md border bg-white p-3"><div><p className="text-sm font-medium text-gray-900">{rule.name}</p><p className="text-xs text-gray-600">{rule.eventType} · {rule.points > 0 ? '+' : ''}{rule.points} {rule.dimension === 'fit' ? 'fit' : 'intenção'}</p></div><Button size="sm" variant="outline" onClick={() => void onDeactivate(rule.id)}>Desativar</Button></div> }
