import { z } from 'zod'
import { missionArtifactHash } from '../mission-command.js'
import type { CapabilityContext, CapabilityDefinition } from '../capability-registry.js'

const uuid=z.string().uuid();const hash=z.string().regex(/^[a-f0-9]{64}$/)
const output=z.object({preview:z.boolean(),entityId:uuid.optional(),versionId:uuid.optional(),contentHash:hash,status:z.string(),activated:z.literal(false),valid:z.boolean().optional(),blockers:z.array(z.string()).optional()})
const common={requiredModules:['campaigns','landing_pages','campaign_launch_agent'],requiredConnections:[] as string[],domain:'acquisition',requiredPermissions:['landing_pages.write'],supportsModes:['shadow','prepare','assisted','autonomous'] as const,readiness:async()=>({ready:true,blockers:[]})}
function contextInput(context:CapabilityContext,input:Record<string,unknown>){if(!context.actionRunId||!context.actor.id)throw new Error('capability_execution_context_required');return{...input,organizationId:context.organizationId,missionId:context.missionId,actionRunId:context.actionRunId,actorId:context.actor.id,idempotencyKey:context.idempotencyKey}}
async function invoke(context:CapabilityContext,key:keyof NonNullable<CapabilityContext['commands']>,input:Record<string,unknown>){const fn=context.commands?.[key];if(!fn)throw new Error('capability_command_unavailable');return fn(contextInput(context,input)) as Promise<{entityId:string;versionId:string;contentHash:string;status:string}>}
const recovery={kind:'compensatable' as const,async compensate(){return{output:{recovered:true},effectProduced:false}}}

export const landingPageCreateDraft:CapabilityDefinition={key:'landing_page.create_draft',version:1,title:'Criar landing page em rascunho',description:'Cria página somente para preview interno.',risk:'low',effect:'draft',approval:'never',idempotency:'required',inputSchema:z.object({name:z.string().min(1).max(160),slug:z.string().regex(/^[a-z0-9-]+$/),title:z.string().min(1).max(240),primaryCtaType:z.enum(['form','whatsapp','phone','external_url']),primaryCtaValue:z.string().min(1).max(500),content:z.record(z.string(),z.unknown()),campaignId:uuid.optional()}),outputSchema:output,...common,recovery,async execute(context,raw){const input=raw as Record<string,unknown>;const contentHash=missionArtifactHash(input);if(context.dryRun)return{output:{preview:true,contentHash,status:'draft',activated:false},effectProduced:false};const result=await invoke(context,'createLandingPageDraft',input);return{output:{preview:false,...result,activated:false},effectProduced:true,sourceRecords:[{type:'landing_page',id:result.entityId},{type:'landing_page_version',id:result.versionId}]}}}

export const leadFormConfigureDraft:CapabilityDefinition={key:'lead_form.configure_draft',version:1,title:'Configurar formulário em rascunho',description:'Configura captação com consentimento explícito sem ativá-la.',risk:'low',effect:'draft',approval:'never',idempotency:'required',inputSchema:z.object({landingPageId:uuid,name:z.string().min(1).max(120),submitLabel:z.string().min(1).max(80),successMessage:z.string().min(1).max(240),consentCode:z.string().min(1).max(100),consentVersion:z.string().min(1).max(50),privacyPolicyVersion:z.string().min(1).max(50),fields:z.array(z.object({fieldName:z.string().min(1).max(100),crmFieldKey:z.string().min(1).max(100),required:z.boolean()})).min(2).max(30)}),outputSchema:output,...common,recovery,async execute(context,raw){const input=raw as Record<string,unknown>;const contentHash=missionArtifactHash(input);if(context.dryRun)return{output:{preview:true,contentHash,status:'draft',activated:false},effectProduced:false};const result=await invoke(context,'createLeadFormDraft',input);return{output:{preview:false,...result,activated:false},effectProduced:true,sourceRecords:[{type:'landing_page_form',id:result.entityId}]}}}

export const campaignAcquisitionAttachDraft:CapabilityDefinition={key:'campaign.acquisition.attach_draft',version:1,title:'Vincular ativo de aquisição',description:'Vincula página, formulário ou tracking ao rascunho.',risk:'low',effect:'draft',approval:'never',idempotency:'required',inputSchema:z.object({campaignVersionId:uuid,assetKind:z.enum(['landing_page','lead_form','tracking']),sourceEntityId:uuid.optional(),payload:z.record(z.string(),z.unknown()),validated:z.boolean().default(false)}),outputSchema:output,...common,recovery,async execute(context,raw){const input=raw as Record<string,unknown>;const contentHash=missionArtifactHash(input.payload);if(context.dryRun)return{output:{preview:true,contentHash,status:input.validated?'validated':'draft',activated:false},effectProduced:false};const result=await invoke(context,'attachAcquisitionAsset',input);return{output:{preview:false,...result,activated:false},effectProduced:true,sourceRecords:[{type:'campaign_acquisition_asset_version',id:result.versionId}]}}}

export const campaignTrackingValidate:CapabilityDefinition={key:'campaign.tracking.validate',version:1,title:'Validar tracking da campanha',description:'Valida UTM e destino sem publicar.',risk:'read_only',effect:'none',approval:'never',idempotency:'none',inputSchema:z.object({utmSource:z.string().min(1),utmMedium:z.string().min(1),utmCampaign:z.string().min(1),landingPageUrl:z.string().url(),conversionEvent:z.string().min(1)}),outputSchema:output,requiredModules:['campaigns','landing_pages'],requiredConnections:[],domain:'measurement',requiredPermissions:['campaign.read'],supportsModes:['shadow','prepare','assisted','autonomous'],readiness:async()=>({ready:true,blockers:[]}),recovery:{kind:'compensatable',async compensate(){return{output:{recovered:true,effect:'none'},effectProduced:false}}},async execute(_context,input){const contentHash=missionArtifactHash(input);return{output:{preview:true,contentHash,status:'validated',activated:false,valid:true,blockers:[]},effectProduced:false}}}
