import { z } from 'zod'
import { missionArtifactHash } from '../mission-command.js'
import { noEffectRecovery, type CapabilityContext, type CapabilityDefinition } from '../capability-registry.js'

const uuid=z.string().uuid();const hash=z.string().regex(/^[a-f0-9]{64}$/);const decimal=z.string().regex(/^\d+(\.\d{1,6})?$/)
const creative=z.object({format:z.enum(['image','video','carousel','text']),headline:z.string().trim().min(1).max(240),body:z.string().trim().min(1).max(5000),sourceIds:z.array(z.string().min(1)).min(1).max(100)})
export const campaignDraftInput=z.object({name:z.string().trim().min(1).max(200),objective:z.enum(['lead_generation','traffic','conversions','awareness']),offer:z.string().trim().min(1).max(2000),audience:z.record(z.string(),z.unknown()),platform:z.enum(['meta','google']),providerConnectionId:uuid,dailyBudgetBrl:decimal,totalBudgetBrl:decimal,startsAt:z.string().datetime(),endsAt:z.string().datetime().optional(),creatives:z.array(creative).min(1).max(20),landingPageId:uuid.optional(),leadFormId:uuid.optional(),trackingPlan:z.record(z.string(),z.string()),sourceIds:z.array(z.string().min(1)).min(1).max(200)})
const artifactOutput=z.object({preview:z.boolean(),entityId:uuid.optional(),versionId:uuid.optional(),contentHash:hash,status:z.string(),activated:z.boolean(),providerReference:z.string().optional(),mutationRunId:uuid.optional()})
const exactProviderInput=z.object({versionId:uuid,expectedContentHash:hash,approvedSubjectHash:hash})
const commandContext=(context:CapabilityContext,input:Record<string,unknown>)=>{if(!context.actionRunId||!context.actor.id)throw new Error('capability_execution_context_required');return{...input,organizationId:context.organizationId,missionId:context.missionId,actionRunId:context.actionRunId,actorId:context.actor.id,idempotencyKey:context.idempotencyKey}}
async function invoke(context:CapabilityContext,key:keyof NonNullable<CapabilityContext['commands']>,input:Record<string,unknown>){const command=context.commands?.[key];if(!command)throw new Error('capability_command_unavailable');return command(commandContext(context,input)) as Promise<{entityId:string;versionId:string;contentHash:string;status:string;providerReference?:string;mutationRunId?:string}>}
const draftCommon={requiredModules:['campaigns','campaign_launch_agent'],requiredConnections:[] as string[],domain:'campaigns',requiredPermissions:['campaign.write'],supportsModes:['shadow','prepare','assisted','autonomous'] as const,readiness:async()=>({ready:true,blockers:[]})}
const providerCommon={requiredModules:['campaigns','campaign_launch_agent'],requiredConnections:['ads_provider'],domain:'campaigns',requiredPermissions:['campaign.write'],supportsModes:['assisted','autonomous'] as const,readiness:async()=>({ready:true,blockers:[]})}

export const campaignStateInspect:CapabilityDefinition={key:'campaign.state.inspect',version:1,title:'Inspecionar campanhas',description:'Lê campanhas e versões locais sem credenciais.',risk:'read_only',effect:'none',approval:'never',idempotency:'none',inputSchema:z.object({}),outputSchema:z.object({campaigns:z.array(z.record(z.string(),z.unknown()))}),requiredModules:['campaigns'],requiredConnections:[],domain:'campaigns',requiredPermissions:['campaign.read'],supportsModes:['shadow','prepare','assisted','autonomous'],readiness:async()=>({ready:true,blockers:[]}),recovery:noEffectRecovery(),async execute(context){const command=context.commands?.inspectCampaignState;if(!command)throw new Error('capability_command_unavailable');const campaigns=await command({organizationId:context.organizationId,missionId:context.missionId,idempotencyKey:context.idempotencyKey});return{output:{campaigns:Array.isArray(campaigns)?campaigns:[]},effectProduced:false}}}

export const campaignCreateDraft:CapabilityDefinition={key:'campaign.create_draft',version:1,title:'Criar rascunho de campanha',description:'Persiste campanha versionada sem publicação externa.',risk:'low',effect:'draft',approval:'never',idempotency:'required',inputSchema:campaignDraftInput,outputSchema:artifactOutput,...draftCommon,recovery:{kind:'compensatable',async compensate(_context,result){return{output:{recovered:true,versionId:(result as {versionId?:string}).versionId},effectProduced:false}}},async execute(context,raw){const input=raw as z.infer<typeof campaignDraftInput>;const contentHash=missionArtifactHash(input);if(context.dryRun)return{output:{preview:true,contentHash,status:'draft',activated:false},effectProduced:false};const result=await invoke(context,'createCampaignDraft',input);return{output:{preview:false,...result,activated:false},effectProduced:true,sourceRecords:[{type:'campaign',id:result.entityId},{type:'campaign_mission_version',id:result.versionId}]}}}

export const marketingCreativeGenerateDraft:CapabilityDefinition={key:'marketing.creative.generate_draft',version:1,title:'Gerar criativo de campanha',description:'Persiste copy e briefing citados como rascunho.',risk:'low',effect:'draft',approval:'never',idempotency:'required',inputSchema:z.object({campaignVersionId:uuid,position:z.number().int().min(0).max(19),creative}),outputSchema:artifactOutput,...draftCommon,recovery:{kind:'compensatable',async compensate(){return{output:{recovered:true},effectProduced:false}}},async execute(context,raw){const input=raw as Record<string,unknown>;const contentHash=missionArtifactHash(input.creative);if(context.dryRun)return{output:{preview:true,contentHash,status:'draft',activated:false},effectProduced:false};const result=await invoke(context,'generateCreativeDraft',input);return{output:{preview:false,...result,activated:false},effectProduced:true,sourceRecords:[{type:'campaign_creative_version',id:result.versionId}]}}}

export const campaignCreativeAttachDraft:CapabilityDefinition={key:'campaign.creative.attach_draft',version:1,title:'Vincular criativo à campanha',description:'Vincula somente a versão exata do criativo.',risk:'low',effect:'draft',approval:'never',idempotency:'required',inputSchema:z.object({campaignVersionId:uuid,creativeVersionId:uuid,expectedContentHash:hash}),outputSchema:artifactOutput,...draftCommon,recovery:{kind:'compensatable',async compensate(){return{output:{recovered:true},effectProduced:false}}},async execute(context,raw){const input=raw as Record<string,unknown>;if(context.dryRun)return{output:{preview:true,contentHash:String(input.expectedContentHash),status:'draft',activated:false},effectProduced:false};const result=await invoke(context,'attachCampaignCreativeDraft',input);return{output:{preview:false,...result,activated:false},effectProduced:true,sourceRecords:[{type:'campaign_creative_version',id:result.versionId}]}}}

function providerCapability(config:{key:string;title:string;command:'createProviderCampaignPaused'|'activateProviderCampaign'|'pauseProviderCampaign';status:string;activated:boolean;approval:'always'|'risk_based'}):CapabilityDefinition{return{key:config.key,version:1,title:config.title,description:'Executa mutação externa idempotente com versão e hash pinados.',risk:'high',effect:'external',approval:config.approval,idempotency:'required',inputSchema:config.command==='createProviderCampaignPaused'?exactProviderInput.extend({maxTotalBudgetBrl:decimal}):exactProviderInput,outputSchema:artifactOutput,...providerCommon,recovery:config.command==='pauseProviderCampaign'?{kind:'irreversible',incidentType:'campaign_pause_requires_reconciliation'}:{kind:'pausable',async contain(context,result){if(!(result as {versionId?:string}).versionId)return{output:{contained:true,reason:'preview_only'},effectProduced:false};const command=context.commands?.pauseProviderCampaign;if(!command)throw new Error('capability_command_unavailable');await command(commandContext(context,{versionId:(result as {versionId:string}).versionId,expectedContentHash:(result as {contentHash:string}).contentHash,approvedSubjectHash:(result as {contentHash:string}).contentHash}));return{output:{contained:true},effectProduced:true}}},async execute(context,raw){const input=raw as Record<string,unknown>;if(context.dryRun)return{output:{preview:true,versionId:String(input.versionId),contentHash:String(input.expectedContentHash),status:config.status,activated:false},effectProduced:false};const result=await invoke(context,config.command,input);return{output:{preview:false,...result,status:config.status,activated:config.activated},effectProduced:true,sourceRecords:[{type:'provider_campaign',id:result.providerReference??result.entityId}],costHints:[{category:'media',amount:'0',currency:'BRL'}]}}}}
export const campaignProviderCreatePaused=providerCapability({key:'campaign.provider.create_paused',title:'Criar campanha pausada no provedor',command:'createProviderCampaignPaused',status:'provider_paused',activated:false,approval:'always'})
export const campaignProviderActivate=providerCapability({key:'campaign.provider.activate',title:'Ativar campanha no provedor',command:'activateProviderCampaign',status:'active',activated:true,approval:'always'})
export const campaignProviderPause=providerCapability({key:'campaign.provider.pause',title:'Pausar campanha no provedor',command:'pauseProviderCampaign',status:'paused',activated:false,approval:'risk_based'})
