import { createHash } from 'node:crypto'
import { z } from 'zod'
import type { ActionPackVersion, PackStepTemplate, RuntimeActionPackVersion } from '../action-pack.js'
import { hashAttributionPolicy, type AttributionPolicy } from '../metrics/attribution.js'

export const CAMPAIGN_LAUNCH_ATTRIBUTION_POLICY:AttributionPolicy={version:1,model:'last_touch',windowDays:30,eligibleEventTypes:['campaign_click','landing_page_submit','lead_created','invoice_paid'],identityResolution:'exact_campaign_utm_or_declared_lead_binding',currency:'BRL',lateEvents:'reopen_evaluation'}
export const campaignLaunchParameters=z.object({icp:z.string().trim().min(3).max(2000),offer:z.string().trim().min(3).max(2000),platform:z.enum(['meta','google']),providerConnectionId:z.string().uuid(),dailyBudgetBrl:z.string().regex(/^\d+(\.\d{1,2})?$/).refine(value=>Number(value)>0),totalBudgetBrl:z.string().regex(/^\d+(\.\d{1,2})?$/).refine(value=>Number(value)>0),targetLeads:z.number().int().min(1).max(100000).default(50),maximumCplBrl:z.string().regex(/^\d+(\.\d{1,2})?$/).default('100'),observationDays:z.number().int().min(1).max(90).default(30),maxTotalCostBrl:z.string().regex(/^\d+(\.\d{1,2})?$/).default('1000'),maxHumanHours:z.string().regex(/^\d+(\.\d{1,2})?$/).default('8'),humanHourlyRateBrl:z.string().regex(/^\d+(\.\d{1,2})?$/).default('100')}).superRefine((value,ctx)=>{if(Number(value.totalBudgetBrl)<Number(value.dailyBudgetBrl))ctx.addIssue({code:'custom',message:'campaign_total_budget_below_daily',path:['totalBudgetBrl']})})
export type CampaignLaunchParameters=z.infer<typeof campaignLaunchParameters>
const rawSteps:Array<{stepKey:string;capabilityKey:string;approval?:boolean;parameters?:Record<string,unknown>}>= [
  {stepKey:'pack.readiness',capabilityKey:'system.readiness.check',parameters:{requiredModules:['campaigns','landing_pages','campaign_launch_agent'],requiredConnections:['ads_provider']}},
  {stepKey:'pack.inspect',capabilityKey:'campaign.state.inspect'},
  {stepKey:'pack.draft_landing_page',capabilityKey:'landing_page.create_draft',parameters:{artifactRef:'resolvedParameters.campaignLaunchArtifacts.acquisition.landingPage'}},
  {stepKey:'pack.draft_lead_form',capabilityKey:'lead_form.configure_draft',parameters:{artifactRef:'resolvedParameters.campaignLaunchArtifacts.acquisition.leadForm',landingPageId:'binding:pack.draft_landing_page.entityId'}},
  {stepKey:'pack.validate_tracking',capabilityKey:'campaign.tracking.validate',parameters:{artifactRef:'resolvedParameters.campaignLaunchArtifacts.acquisition.trackingPlan'}},
  {stepKey:'pack.draft_campaign',capabilityKey:'campaign.create_draft',parameters:{artifactRef:'resolvedParameters.campaignLaunchArtifacts'}},
  {stepKey:'pack.draft_creative',capabilityKey:'marketing.creative.generate_draft',parameters:{campaignVersionId:'binding:pack.draft_campaign.versionId',position:0,artifactRef:'resolvedParameters.campaignLaunchArtifacts.creativeSet.creatives.0'}},
  {stepKey:'pack.attach_creative',capabilityKey:'campaign.creative.attach_draft',parameters:{campaignVersionId:'binding:pack.draft_campaign.versionId',creativeVersionId:'binding:pack.draft_creative.versionId',expectedContentHash:'binding:pack.draft_creative.contentHash'}},
  {stepKey:'pack.attach_landing_page',capabilityKey:'campaign.acquisition.attach_draft',parameters:{campaignVersionId:'binding:pack.draft_campaign.versionId',assetKind:'landing_page',sourceEntityId:'binding:pack.draft_landing_page.entityId',payload:{versionId:'binding:pack.draft_landing_page.versionId',contentHash:'binding:pack.draft_landing_page.contentHash'}}},
  {stepKey:'pack.attach_lead_form',capabilityKey:'campaign.acquisition.attach_draft',parameters:{campaignVersionId:'binding:pack.draft_campaign.versionId',assetKind:'lead_form',sourceEntityId:'binding:pack.draft_lead_form.entityId',payload:{contentHash:'binding:pack.draft_lead_form.contentHash'}}},
  {stepKey:'pack.create_provider_paused',capabilityKey:'campaign.provider.create_paused',approval:true,parameters:{versionId:'binding:pack.draft_campaign.versionId',expectedContentHash:'binding:pack.draft_campaign.contentHash',approvedSubjectHash:'binding:pack.draft_campaign.contentHash',maxTotalBudgetBrl:'runtime'}},
  {stepKey:'pack.approve_launch',capabilityKey:'system.approval.await',approval:true,parameters:{approvalType:'external_effect',subject:{artifactSet:'campaign_launch',providerState:'paused'}}},
  {stepKey:'pack.activate',capabilityKey:'campaign.provider.activate',approval:true,parameters:{versionId:'binding:pack.draft_campaign.versionId',expectedContentHash:'binding:pack.draft_campaign.contentHash',approvedSubjectHash:'binding:pack.draft_campaign.contentHash'}},
  {stepKey:'pack.wait_observation',capabilityKey:'system.signal.wait',parameters:{durationHours:24}},
  {stepKey:'pack.collect_metrics_and_costs',capabilityKey:'campaign.metrics.snapshot',parameters:{campaignId:'binding:pack.draft_campaign.entityId'}},
  {stepKey:'pack.evaluate',capabilityKey:'system.evaluation.checkpoint',parameters:{checkpointKey:'campaign_launch_24h',targetRevenueBrl:'0'}},
]
const topologySteps:PackStepTemplate[]=rawSteps.map((step,index)=>({stepKey:step.stepKey,capabilityKey:step.capabilityKey,capabilityVersion:1,dependsOn:index===0?[]:[rawSteps[index-1]!.stepKey],approvalRequired:step.approval??false,protected:true,defaultParameters:step.parameters??{}}))
const definition:Omit<ActionPackVersion,'contentHash'>={key:'campaign_launch',semanticVersion:'1.0.0',schemaVersion:1,outcomeType:'paid_campaign_launch',status:'published',parameterSchema:{type:'object',required:['icp','offer','platform','providerConnectionId','dailyBudgetBrl','totalBudgetBrl'],properties:{icp:{type:'string'},offer:{type:'string'},platform:{enum:['meta','google']},providerConnectionId:{type:'string',format:'uuid'},dailyBudgetBrl:{type:'string',format:'decimal'},totalBudgetBrl:{type:'string',format:'decimal'},targetLeads:{type:'integer'},maximumCplBrl:{type:'string',format:'decimal'},observationDays:{type:'integer'}}},readinessSpec:{requiredModules:['campaigns','landing_pages','campaign_launch_agent'],requiredConnections:['ads_provider'],requiredKnowledge:['company.icp','company.offer','brand.rules'],correctionLinks:{provider:'/integrations',contract:'/platform/contracts',knowledge:'/knowledge'}},topologyTemplate:{steps:topologySteps},protectedStepKeys:rawSteps.map(step=>step.stepKey),extensionPoints:[{key:'funnel_binding',afterStepKey:'pack.inspect',beforeStepKey:'pack.draft_landing_page',allowedCapabilities:[{key:'crm.pipeline.inspect',versions:[1]}],maxAdditionalSteps:1}],allowedCapabilities:[...new Set(rawSteps.map(step=>step.capabilityKey).concat(['crm.pipeline.inspect','campaign.provider.pause']))].map(key=>({key,versions:[1],required:rawSteps.some(step=>step.capabilityKey===key)})),metricSpec:{primary:[{key:'leads',unit:'count'},{key:'qualified_leads',unit:'count'},{key:'attributed_revenue_brl',unit:'BRL',attributionPolicy:CAMPAIGN_LAUNCH_ATTRIBUTION_POLICY,attributionPolicyHash:hashAttributionPolicy(CAMPAIGN_LAUNCH_ATTRIBUTION_POLICY)}],leading:['impressions','clicks','ctr','landing_conversion_rate'],economics:['spend_brl','total_execution_cost_brl','cpl_brl','mroi'],guardrails:['total_budget_brl','daily_budget_brl','consent_blocks','tracking_failure','complaint_rate'],unknownPolicy:'revenue_and_mroi_unknown_when_identity_or_tracking_unresolved'},economicsSpec:{currency:'BRL',formulas:{totalCost:'spendBrl+sum(actual_cost_entries_brl)',cpl:'totalCost/leads',mroi:'(attributedRevenueBrl-totalCost)/totalCost',valueCostRatio:'attributedRevenueBrl/totalCost',valuePerHumanHour:'attributedRevenueBrl/humanHours'},zeroDenominator:'not_applicable',trackFromFirstRun:true},policyDefaults:{mode:'assisted',ownershipMode:'exclusive',conflictPolicy:'mission_wins',providerCreatePaused:true,activationApprovalRequired:true,budgetChangeApprovalRequired:true,activationContractFlag:'campaign_launch_agent',activationCapabilitiesDisabledByDefault:true}}
export const CAMPAIGN_LAUNCH_PACK_V1:RuntimeActionPackVersion<CampaignLaunchParameters>={...definition,parameters:campaignLaunchParameters,contentHash:hashDefinition(definition)}
export function createCampaignLaunchPlan(parameters:CampaignLaunchParameters){return{schemaVersion:1 as const,packKey:CAMPAIGN_LAUNCH_PACK_V1.key,packVersion:CAMPAIGN_LAUNCH_PACK_V1.semanticVersion,packContentHash:CAMPAIGN_LAUNCH_PACK_V1.contentHash,parameters,deviations:[],steps:topologySteps.map(step=>({stepKey:step.stepKey,capabilityKey:step.capabilityKey,capabilityVersion:step.capabilityVersion,dependsOn:[...step.dependsOn],parameters:Object.fromEntries(Object.entries(step.defaultParameters).map(([key,value])=>[key,value==='runtime'?parameters.totalBudgetBrl:value])),approvalRequired:step.approvalRequired,protected:true})),estimatedEconomics:{currency:'BRL',mediaBudgetBrl:parameters.totalBudgetBrl,maxTotalCostBrl:parameters.maxTotalCostBrl,maxHumanHours:parameters.maxHumanHours}}}
function hashDefinition(value:unknown){return createHash('sha256').update(stable(value)).digest('hex')}
function stable(value:unknown):string{if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;if(value&&typeof value==='object')return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(',')}}`;return JSON.stringify(value)}
